FROM rwngallego/asdf:centos7.7-elixir

ENV MIX_ENV=prod
ENV PORT=4000

COPY ./ /code

# We build the release in /app/bside-api
RUN cd /code && \
  mix deps.get --only prod && \
  mix release --path /app/bside-api && \
  cd /app/bside-api && rm -rf /code

# Last setup
ENV HOME=/app
WORKDIR /app/bside-api
