FROM elixir:1.10.1-slim as build

SHELL ["/bin/bash", "-c"]

RUN apt-get update

RUN mix local.hex --force
RUN mix local.rebar --force

ENV MIX_ENV=prod
ENV PORT=4000

COPY ./ /code

# We build the release in /app
RUN cd /code && \
  mix deps.get --only prod && \
  mix release --path /app && \
  cd /app && rm -rf /code

# Last setup
RUN chown -R nobody: /app
USER nobody
ENV HOME=/app

WORKDIR /app

CMD ["/bin/bash", "-c"]