version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - bside-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

networks:
  bside-net:
    name: bside-net